# Generated by Django 4.2 on 2024-12-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("with_chatGPT", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="role",
        ),
    ]
