# Generated by Django 4.2 on 2024-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("conversation_id", models.CharField(max_length=200)),
                ("lang_setting", models.CharField(max_length=10)),
            ],
        ),
    ]
