# Generated by Django 4.2 on 2024-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="id",
        ),
        migrations.AlterField(
            model_name="session",
            name="conversation_id",
            field=models.CharField(max_length=200, verbose_name="会話id"),
        ),
        migrations.AlterField(
            model_name="session",
            name="lang_setting",
            field=models.CharField(max_length=10, verbose_name="言語設定"),
        ),
        migrations.AlterField(
            model_name="session",
            name="user_id",
            field=models.CharField(
                max_length=200,
                primary_key=True,
                serialize=False,
                verbose_name="line識別子",
            ),
        ),
    ]
