# Generated by Django 4.2 on 2024-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, null=True, verbose_name="システムプロンプト"
                    ),
                ),
                (
                    "prompt",
                    models.TextField(blank=True, null=True, verbose_name="プロンプト"),
                ),
            ],
        ),
    ]
