# Generated by Django 4.2 on 2025-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historymodel",
            name="conversation_id",
            field=models.CharField(default="", max_length=200, verbose_name="会話id"),
        ),
    ]
